// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airportdata.proto

package AirportData;

public final class AirportDataProto {
  private AirportDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AirportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:airportdata.Airport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string state = 1;</code>
     */
    boolean hasState();
    /**
     * <code>required string state = 1;</code>
     */
    java.lang.String getState();
    /**
     * <code>required string state = 1;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string code = 3;</code>
     */
    boolean hasCode();
    /**
     * <code>required string code = 3;</code>
     */
    java.lang.String getCode();
    /**
     * <code>required string code = 3;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>required double lat = 4;</code>
     */
    boolean hasLat();
    /**
     * <code>required double lat = 4;</code>
     */
    double getLat();

    /**
     * <code>required double lon = 5;</code>
     */
    boolean hasLon();
    /**
     * <code>required double lon = 5;</code>
     */
    double getLon();
  }
  /**
   * Protobuf type {@code airportdata.Airport}
   */
  public  static final class Airport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:airportdata.Airport)
      AirportOrBuilder {
    // Use Airport.newBuilder() to construct.
    private Airport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Airport() {
      state_ = "";
      name_ = "";
      code_ = "";
      lat_ = 0D;
      lon_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Airport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              state_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              code_ = bs;
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              lat_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              lon_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AirportData.AirportDataProto.internal_static_airportdata_Airport_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AirportData.AirportDataProto.internal_static_airportdata_Airport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AirportData.AirportDataProto.Airport.class, AirportData.AirportDataProto.Airport.Builder.class);
    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object state_;
    /**
     * <code>required string state = 1;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string state = 1;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          state_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string state = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object code_;
    /**
     * <code>required string code = 3;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string code = 3;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string code = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAT_FIELD_NUMBER = 4;
    private double lat_;
    /**
     * <code>required double lat = 4;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double lat = 4;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int LON_FIELD_NUMBER = 5;
    private double lon_;
    /**
     * <code>required double lon = 5;</code>
     */
    public boolean hasLon() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double lon = 5;</code>
     */
    public double getLon() {
      return lon_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, lat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, lon_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, lat_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, lon_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AirportData.AirportDataProto.Airport)) {
        return super.equals(obj);
      }
      AirportData.AirportDataProto.Airport other = (AirportData.AirportDataProto.Airport) obj;

      boolean result = true;
      result = result && (hasState() == other.hasState());
      if (hasState()) {
        result = result && getState()
            .equals(other.getState());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasCode() == other.hasCode());
      if (hasCode()) {
        result = result && getCode()
            .equals(other.getCode());
      }
      result = result && (hasLat() == other.hasLat());
      if (hasLat()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLat())
            == java.lang.Double.doubleToLongBits(
                other.getLat()));
      }
      result = result && (hasLon() == other.hasLon());
      if (hasLon()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLon())
            == java.lang.Double.doubleToLongBits(
                other.getLon()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
      }
      if (hasLat()) {
        hash = (37 * hash) + LAT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLat()));
      }
      if (hasLon()) {
        hash = (37 * hash) + LON_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLon()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AirportData.AirportDataProto.Airport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AirportData.AirportDataProto.Airport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AirportData.AirportDataProto.Airport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AirportData.AirportDataProto.Airport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AirportData.AirportDataProto.Airport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AirportData.AirportDataProto.Airport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AirportData.AirportDataProto.Airport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AirportData.AirportDataProto.Airport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AirportData.AirportDataProto.Airport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AirportData.AirportDataProto.Airport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AirportData.AirportDataProto.Airport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code airportdata.Airport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:airportdata.Airport)
        AirportData.AirportDataProto.AirportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AirportData.AirportDataProto.internal_static_airportdata_Airport_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AirportData.AirportDataProto.internal_static_airportdata_Airport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AirportData.AirportDataProto.Airport.class, AirportData.AirportDataProto.Airport.Builder.class);
      }

      // Construct using AirportData.AirportDataProto.Airport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        lon_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AirportData.AirportDataProto.internal_static_airportdata_Airport_descriptor;
      }

      public AirportData.AirportDataProto.Airport getDefaultInstanceForType() {
        return AirportData.AirportDataProto.Airport.getDefaultInstance();
      }

      public AirportData.AirportDataProto.Airport build() {
        AirportData.AirportDataProto.Airport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AirportData.AirportDataProto.Airport buildPartial() {
        AirportData.AirportDataProto.Airport result = new AirportData.AirportDataProto.Airport(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lon_ = lon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AirportData.AirportDataProto.Airport) {
          return mergeFrom((AirportData.AirportDataProto.Airport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AirportData.AirportDataProto.Airport other) {
        if (other == AirportData.AirportDataProto.Airport.getDefaultInstance()) return this;
        if (other.hasState()) {
          bitField0_ |= 0x00000001;
          state_ = other.state_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCode()) {
          bitField0_ |= 0x00000004;
          code_ = other.code_;
          onChanged();
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasState()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasCode()) {
          return false;
        }
        if (!hasLat()) {
          return false;
        }
        if (!hasLon()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AirportData.AirportDataProto.Airport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AirportData.AirportDataProto.Airport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object state_ = "";
      /**
       * <code>required string state = 1;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string state = 1;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            state_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string state = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string state = 1;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 1;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 1;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>required string code = 3;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string code = 3;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string code = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string code = 3;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 3;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 3;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        code_ = value;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <code>required double lat = 4;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double lat = 4;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>required double lat = 4;</code>
       */
      public Builder setLat(double value) {
        bitField0_ |= 0x00000008;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double lat = 4;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lat_ = 0D;
        onChanged();
        return this;
      }

      private double lon_ ;
      /**
       * <code>required double lon = 5;</code>
       */
      public boolean hasLon() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double lon = 5;</code>
       */
      public double getLon() {
        return lon_;
      }
      /**
       * <code>required double lon = 5;</code>
       */
      public Builder setLon(double value) {
        bitField0_ |= 0x00000010;
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double lon = 5;</code>
       */
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lon_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:airportdata.Airport)
    }

    // @@protoc_insertion_point(class_scope:airportdata.Airport)
    private static final AirportData.AirportDataProto.Airport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AirportData.AirportDataProto.Airport();
    }

    public static AirportData.AirportDataProto.Airport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Airport>
        PARSER = new com.google.protobuf.AbstractParser<Airport>() {
      public Airport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Airport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Airport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Airport> getParserForType() {
      return PARSER;
    }

    public AirportData.AirportDataProto.Airport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AirportListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:airportdata.AirportList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    java.util.List<AirportData.AirportDataProto.Airport> 
        getAirportList();
    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    AirportData.AirportDataProto.Airport getAirport(int index);
    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    int getAirportCount();
    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    java.util.List<? extends AirportData.AirportDataProto.AirportOrBuilder> 
        getAirportOrBuilderList();
    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    AirportData.AirportDataProto.AirportOrBuilder getAirportOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code airportdata.AirportList}
   */
  public  static final class AirportList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:airportdata.AirportList)
      AirportListOrBuilder {
    // Use AirportList.newBuilder() to construct.
    private AirportList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AirportList() {
      airport_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AirportList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                airport_ = new java.util.ArrayList<AirportData.AirportDataProto.Airport>();
                mutable_bitField0_ |= 0x00000001;
              }
              airport_.add(
                  input.readMessage(AirportData.AirportDataProto.Airport.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          airport_ = java.util.Collections.unmodifiableList(airport_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AirportData.AirportDataProto.internal_static_airportdata_AirportList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AirportData.AirportDataProto.internal_static_airportdata_AirportList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AirportData.AirportDataProto.AirportList.class, AirportData.AirportDataProto.AirportList.Builder.class);
    }

    public static final int AIRPORT_FIELD_NUMBER = 1;
    private java.util.List<AirportData.AirportDataProto.Airport> airport_;
    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    public java.util.List<AirportData.AirportDataProto.Airport> getAirportList() {
      return airport_;
    }
    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    public java.util.List<? extends AirportData.AirportDataProto.AirportOrBuilder> 
        getAirportOrBuilderList() {
      return airport_;
    }
    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    public int getAirportCount() {
      return airport_.size();
    }
    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    public AirportData.AirportDataProto.Airport getAirport(int index) {
      return airport_.get(index);
    }
    /**
     * <code>repeated .airportdata.Airport airport = 1;</code>
     */
    public AirportData.AirportDataProto.AirportOrBuilder getAirportOrBuilder(
        int index) {
      return airport_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getAirportCount(); i++) {
        if (!getAirport(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < airport_.size(); i++) {
        output.writeMessage(1, airport_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < airport_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, airport_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AirportData.AirportDataProto.AirportList)) {
        return super.equals(obj);
      }
      AirportData.AirportDataProto.AirportList other = (AirportData.AirportDataProto.AirportList) obj;

      boolean result = true;
      result = result && getAirportList()
          .equals(other.getAirportList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAirportCount() > 0) {
        hash = (37 * hash) + AIRPORT_FIELD_NUMBER;
        hash = (53 * hash) + getAirportList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AirportData.AirportDataProto.AirportList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AirportData.AirportDataProto.AirportList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AirportData.AirportDataProto.AirportList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AirportData.AirportDataProto.AirportList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AirportData.AirportDataProto.AirportList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AirportData.AirportDataProto.AirportList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AirportData.AirportDataProto.AirportList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AirportData.AirportDataProto.AirportList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AirportData.AirportDataProto.AirportList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AirportData.AirportDataProto.AirportList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AirportData.AirportDataProto.AirportList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code airportdata.AirportList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:airportdata.AirportList)
        AirportData.AirportDataProto.AirportListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AirportData.AirportDataProto.internal_static_airportdata_AirportList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AirportData.AirportDataProto.internal_static_airportdata_AirportList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AirportData.AirportDataProto.AirportList.class, AirportData.AirportDataProto.AirportList.Builder.class);
      }

      // Construct using AirportData.AirportDataProto.AirportList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAirportFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (airportBuilder_ == null) {
          airport_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          airportBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AirportData.AirportDataProto.internal_static_airportdata_AirportList_descriptor;
      }

      public AirportData.AirportDataProto.AirportList getDefaultInstanceForType() {
        return AirportData.AirportDataProto.AirportList.getDefaultInstance();
      }

      public AirportData.AirportDataProto.AirportList build() {
        AirportData.AirportDataProto.AirportList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AirportData.AirportDataProto.AirportList buildPartial() {
        AirportData.AirportDataProto.AirportList result = new AirportData.AirportDataProto.AirportList(this);
        int from_bitField0_ = bitField0_;
        if (airportBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            airport_ = java.util.Collections.unmodifiableList(airport_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.airport_ = airport_;
        } else {
          result.airport_ = airportBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AirportData.AirportDataProto.AirportList) {
          return mergeFrom((AirportData.AirportDataProto.AirportList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AirportData.AirportDataProto.AirportList other) {
        if (other == AirportData.AirportDataProto.AirportList.getDefaultInstance()) return this;
        if (airportBuilder_ == null) {
          if (!other.airport_.isEmpty()) {
            if (airport_.isEmpty()) {
              airport_ = other.airport_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAirportIsMutable();
              airport_.addAll(other.airport_);
            }
            onChanged();
          }
        } else {
          if (!other.airport_.isEmpty()) {
            if (airportBuilder_.isEmpty()) {
              airportBuilder_.dispose();
              airportBuilder_ = null;
              airport_ = other.airport_;
              bitField0_ = (bitField0_ & ~0x00000001);
              airportBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAirportFieldBuilder() : null;
            } else {
              airportBuilder_.addAllMessages(other.airport_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAirportCount(); i++) {
          if (!getAirport(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AirportData.AirportDataProto.AirportList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AirportData.AirportDataProto.AirportList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<AirportData.AirportDataProto.Airport> airport_ =
        java.util.Collections.emptyList();
      private void ensureAirportIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          airport_ = new java.util.ArrayList<AirportData.AirportDataProto.Airport>(airport_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AirportData.AirportDataProto.Airport, AirportData.AirportDataProto.Airport.Builder, AirportData.AirportDataProto.AirportOrBuilder> airportBuilder_;

      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public java.util.List<AirportData.AirportDataProto.Airport> getAirportList() {
        if (airportBuilder_ == null) {
          return java.util.Collections.unmodifiableList(airport_);
        } else {
          return airportBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public int getAirportCount() {
        if (airportBuilder_ == null) {
          return airport_.size();
        } else {
          return airportBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public AirportData.AirportDataProto.Airport getAirport(int index) {
        if (airportBuilder_ == null) {
          return airport_.get(index);
        } else {
          return airportBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public Builder setAirport(
          int index, AirportData.AirportDataProto.Airport value) {
        if (airportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAirportIsMutable();
          airport_.set(index, value);
          onChanged();
        } else {
          airportBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public Builder setAirport(
          int index, AirportData.AirportDataProto.Airport.Builder builderForValue) {
        if (airportBuilder_ == null) {
          ensureAirportIsMutable();
          airport_.set(index, builderForValue.build());
          onChanged();
        } else {
          airportBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public Builder addAirport(AirportData.AirportDataProto.Airport value) {
        if (airportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAirportIsMutable();
          airport_.add(value);
          onChanged();
        } else {
          airportBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public Builder addAirport(
          int index, AirportData.AirportDataProto.Airport value) {
        if (airportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAirportIsMutable();
          airport_.add(index, value);
          onChanged();
        } else {
          airportBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public Builder addAirport(
          AirportData.AirportDataProto.Airport.Builder builderForValue) {
        if (airportBuilder_ == null) {
          ensureAirportIsMutable();
          airport_.add(builderForValue.build());
          onChanged();
        } else {
          airportBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public Builder addAirport(
          int index, AirportData.AirportDataProto.Airport.Builder builderForValue) {
        if (airportBuilder_ == null) {
          ensureAirportIsMutable();
          airport_.add(index, builderForValue.build());
          onChanged();
        } else {
          airportBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public Builder addAllAirport(
          java.lang.Iterable<? extends AirportData.AirportDataProto.Airport> values) {
        if (airportBuilder_ == null) {
          ensureAirportIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, airport_);
          onChanged();
        } else {
          airportBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public Builder clearAirport() {
        if (airportBuilder_ == null) {
          airport_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          airportBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public Builder removeAirport(int index) {
        if (airportBuilder_ == null) {
          ensureAirportIsMutable();
          airport_.remove(index);
          onChanged();
        } else {
          airportBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public AirportData.AirportDataProto.Airport.Builder getAirportBuilder(
          int index) {
        return getAirportFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public AirportData.AirportDataProto.AirportOrBuilder getAirportOrBuilder(
          int index) {
        if (airportBuilder_ == null) {
          return airport_.get(index);  } else {
          return airportBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public java.util.List<? extends AirportData.AirportDataProto.AirportOrBuilder> 
           getAirportOrBuilderList() {
        if (airportBuilder_ != null) {
          return airportBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(airport_);
        }
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public AirportData.AirportDataProto.Airport.Builder addAirportBuilder() {
        return getAirportFieldBuilder().addBuilder(
            AirportData.AirportDataProto.Airport.getDefaultInstance());
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public AirportData.AirportDataProto.Airport.Builder addAirportBuilder(
          int index) {
        return getAirportFieldBuilder().addBuilder(
            index, AirportData.AirportDataProto.Airport.getDefaultInstance());
      }
      /**
       * <code>repeated .airportdata.Airport airport = 1;</code>
       */
      public java.util.List<AirportData.AirportDataProto.Airport.Builder> 
           getAirportBuilderList() {
        return getAirportFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AirportData.AirportDataProto.Airport, AirportData.AirportDataProto.Airport.Builder, AirportData.AirportDataProto.AirportOrBuilder> 
          getAirportFieldBuilder() {
        if (airportBuilder_ == null) {
          airportBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AirportData.AirportDataProto.Airport, AirportData.AirportDataProto.Airport.Builder, AirportData.AirportDataProto.AirportOrBuilder>(
                  airport_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          airport_ = null;
        }
        return airportBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:airportdata.AirportList)
    }

    // @@protoc_insertion_point(class_scope:airportdata.AirportList)
    private static final AirportData.AirportDataProto.AirportList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AirportData.AirportDataProto.AirportList();
    }

    public static AirportData.AirportDataProto.AirportList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AirportList>
        PARSER = new com.google.protobuf.AbstractParser<AirportList>() {
      public AirportList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AirportList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AirportList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AirportList> getParserForType() {
      return PARSER;
    }

    public AirportData.AirportDataProto.AirportList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airportdata_Airport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airportdata_Airport_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_airportdata_AirportList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_airportdata_AirportList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021airportdata.proto\022\013airportdata\"N\n\007Airp" +
      "ort\022\r\n\005state\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\014\n\004code" +
      "\030\003 \002(\t\022\013\n\003lat\030\004 \002(\001\022\013\n\003lon\030\005 \002(\001\"4\n\013Airp" +
      "ortList\022%\n\007airport\030\001 \003(\0132\024.airportdata.A" +
      "irportB\037\n\013AirportDataB\020AirportDataProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_airportdata_Airport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_airportdata_Airport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airportdata_Airport_descriptor,
        new java.lang.String[] { "State", "Name", "Code", "Lat", "Lon", });
    internal_static_airportdata_AirportList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_airportdata_AirportList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_airportdata_AirportList_descriptor,
        new java.lang.String[] { "Airport", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
