// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: placedata.proto

package PlaceData;

public final class PlaceDataProto {
  private PlaceDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlaceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:placedata.Place)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string state = 1;</code>
     */
    boolean hasState();
    /**
     * <code>required string state = 1;</code>
     */
    java.lang.String getState();
    /**
     * <code>required string state = 1;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required double lat = 3;</code>
     */
    boolean hasLat();
    /**
     * <code>required double lat = 3;</code>
     */
    double getLat();

    /**
     * <code>required double lon = 4;</code>
     */
    boolean hasLon();
    /**
     * <code>required double lon = 4;</code>
     */
    double getLon();
  }
  /**
   * Protobuf type {@code placedata.Place}
   */
  public  static final class Place extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:placedata.Place)
      PlaceOrBuilder {
    // Use Place.newBuilder() to construct.
    private Place(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Place() {
      state_ = "";
      name_ = "";
      lat_ = 0D;
      lon_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Place(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              state_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              lat_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              lon_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlaceData.PlaceDataProto.internal_static_placedata_Place_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlaceData.PlaceDataProto.internal_static_placedata_Place_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlaceData.PlaceDataProto.Place.class, PlaceData.PlaceDataProto.Place.Builder.class);
    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object state_;
    /**
     * <code>required string state = 1;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string state = 1;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          state_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string state = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAT_FIELD_NUMBER = 3;
    private double lat_;
    /**
     * <code>required double lat = 3;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double lat = 3;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int LON_FIELD_NUMBER = 4;
    private double lon_;
    /**
     * <code>required double lon = 4;</code>
     */
    public boolean hasLon() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double lon = 4;</code>
     */
    public double getLon() {
      return lon_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, lat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, lon_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, lat_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, lon_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlaceData.PlaceDataProto.Place)) {
        return super.equals(obj);
      }
      PlaceData.PlaceDataProto.Place other = (PlaceData.PlaceDataProto.Place) obj;

      boolean result = true;
      result = result && (hasState() == other.hasState());
      if (hasState()) {
        result = result && getState()
            .equals(other.getState());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasLat() == other.hasLat());
      if (hasLat()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLat())
            == java.lang.Double.doubleToLongBits(
                other.getLat()));
      }
      result = result && (hasLon() == other.hasLon());
      if (hasLon()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLon())
            == java.lang.Double.doubleToLongBits(
                other.getLon()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasLat()) {
        hash = (37 * hash) + LAT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLat()));
      }
      if (hasLon()) {
        hash = (37 * hash) + LON_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLon()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlaceData.PlaceDataProto.Place parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlaceData.PlaceDataProto.Place parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlaceData.PlaceDataProto.Place parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlaceData.PlaceDataProto.Place parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlaceData.PlaceDataProto.Place parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlaceData.PlaceDataProto.Place parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlaceData.PlaceDataProto.Place parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlaceData.PlaceDataProto.Place parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlaceData.PlaceDataProto.Place parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlaceData.PlaceDataProto.Place parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlaceData.PlaceDataProto.Place prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code placedata.Place}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:placedata.Place)
        PlaceData.PlaceDataProto.PlaceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlaceData.PlaceDataProto.internal_static_placedata_Place_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlaceData.PlaceDataProto.internal_static_placedata_Place_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlaceData.PlaceDataProto.Place.class, PlaceData.PlaceDataProto.Place.Builder.class);
      }

      // Construct using PlaceData.PlaceDataProto.Place.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        lon_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlaceData.PlaceDataProto.internal_static_placedata_Place_descriptor;
      }

      public PlaceData.PlaceDataProto.Place getDefaultInstanceForType() {
        return PlaceData.PlaceDataProto.Place.getDefaultInstance();
      }

      public PlaceData.PlaceDataProto.Place build() {
        PlaceData.PlaceDataProto.Place result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PlaceData.PlaceDataProto.Place buildPartial() {
        PlaceData.PlaceDataProto.Place result = new PlaceData.PlaceDataProto.Place(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lon_ = lon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlaceData.PlaceDataProto.Place) {
          return mergeFrom((PlaceData.PlaceDataProto.Place)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlaceData.PlaceDataProto.Place other) {
        if (other == PlaceData.PlaceDataProto.Place.getDefaultInstance()) return this;
        if (other.hasState()) {
          bitField0_ |= 0x00000001;
          state_ = other.state_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasState()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasLat()) {
          return false;
        }
        if (!hasLon()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlaceData.PlaceDataProto.Place parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlaceData.PlaceDataProto.Place) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object state_ = "";
      /**
       * <code>required string state = 1;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string state = 1;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            state_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string state = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string state = 1;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 1;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>required string state = 1;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        state_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <code>required double lat = 3;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double lat = 3;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>required double lat = 3;</code>
       */
      public Builder setLat(double value) {
        bitField0_ |= 0x00000004;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double lat = 3;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lat_ = 0D;
        onChanged();
        return this;
      }

      private double lon_ ;
      /**
       * <code>required double lon = 4;</code>
       */
      public boolean hasLon() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double lon = 4;</code>
       */
      public double getLon() {
        return lon_;
      }
      /**
       * <code>required double lon = 4;</code>
       */
      public Builder setLon(double value) {
        bitField0_ |= 0x00000008;
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double lon = 4;</code>
       */
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lon_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:placedata.Place)
    }

    // @@protoc_insertion_point(class_scope:placedata.Place)
    private static final PlaceData.PlaceDataProto.Place DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlaceData.PlaceDataProto.Place();
    }

    public static PlaceData.PlaceDataProto.Place getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Place>
        PARSER = new com.google.protobuf.AbstractParser<Place>() {
      public Place parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Place(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Place> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Place> getParserForType() {
      return PARSER;
    }

    public PlaceData.PlaceDataProto.Place getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlaceListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:placedata.PlaceList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    java.util.List<PlaceData.PlaceDataProto.Place> 
        getPlaceList();
    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    PlaceData.PlaceDataProto.Place getPlace(int index);
    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    int getPlaceCount();
    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    java.util.List<? extends PlaceData.PlaceDataProto.PlaceOrBuilder> 
        getPlaceOrBuilderList();
    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    PlaceData.PlaceDataProto.PlaceOrBuilder getPlaceOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code placedata.PlaceList}
   */
  public  static final class PlaceList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:placedata.PlaceList)
      PlaceListOrBuilder {
    // Use PlaceList.newBuilder() to construct.
    private PlaceList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlaceList() {
      place_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlaceList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                place_ = new java.util.ArrayList<PlaceData.PlaceDataProto.Place>();
                mutable_bitField0_ |= 0x00000001;
              }
              place_.add(
                  input.readMessage(PlaceData.PlaceDataProto.Place.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          place_ = java.util.Collections.unmodifiableList(place_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlaceData.PlaceDataProto.internal_static_placedata_PlaceList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlaceData.PlaceDataProto.internal_static_placedata_PlaceList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlaceData.PlaceDataProto.PlaceList.class, PlaceData.PlaceDataProto.PlaceList.Builder.class);
    }

    public static final int PLACE_FIELD_NUMBER = 1;
    private java.util.List<PlaceData.PlaceDataProto.Place> place_;
    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    public java.util.List<PlaceData.PlaceDataProto.Place> getPlaceList() {
      return place_;
    }
    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    public java.util.List<? extends PlaceData.PlaceDataProto.PlaceOrBuilder> 
        getPlaceOrBuilderList() {
      return place_;
    }
    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    public int getPlaceCount() {
      return place_.size();
    }
    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    public PlaceData.PlaceDataProto.Place getPlace(int index) {
      return place_.get(index);
    }
    /**
     * <code>repeated .placedata.Place place = 1;</code>
     */
    public PlaceData.PlaceDataProto.PlaceOrBuilder getPlaceOrBuilder(
        int index) {
      return place_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPlaceCount(); i++) {
        if (!getPlace(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < place_.size(); i++) {
        output.writeMessage(1, place_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < place_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, place_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlaceData.PlaceDataProto.PlaceList)) {
        return super.equals(obj);
      }
      PlaceData.PlaceDataProto.PlaceList other = (PlaceData.PlaceDataProto.PlaceList) obj;

      boolean result = true;
      result = result && getPlaceList()
          .equals(other.getPlaceList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPlaceCount() > 0) {
        hash = (37 * hash) + PLACE_FIELD_NUMBER;
        hash = (53 * hash) + getPlaceList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlaceData.PlaceDataProto.PlaceList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlaceData.PlaceDataProto.PlaceList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlaceData.PlaceDataProto.PlaceList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlaceData.PlaceDataProto.PlaceList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlaceData.PlaceDataProto.PlaceList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlaceData.PlaceDataProto.PlaceList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlaceData.PlaceDataProto.PlaceList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlaceData.PlaceDataProto.PlaceList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlaceData.PlaceDataProto.PlaceList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlaceData.PlaceDataProto.PlaceList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlaceData.PlaceDataProto.PlaceList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code placedata.PlaceList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:placedata.PlaceList)
        PlaceData.PlaceDataProto.PlaceListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlaceData.PlaceDataProto.internal_static_placedata_PlaceList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlaceData.PlaceDataProto.internal_static_placedata_PlaceList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlaceData.PlaceDataProto.PlaceList.class, PlaceData.PlaceDataProto.PlaceList.Builder.class);
      }

      // Construct using PlaceData.PlaceDataProto.PlaceList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlaceFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (placeBuilder_ == null) {
          place_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          placeBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlaceData.PlaceDataProto.internal_static_placedata_PlaceList_descriptor;
      }

      public PlaceData.PlaceDataProto.PlaceList getDefaultInstanceForType() {
        return PlaceData.PlaceDataProto.PlaceList.getDefaultInstance();
      }

      public PlaceData.PlaceDataProto.PlaceList build() {
        PlaceData.PlaceDataProto.PlaceList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PlaceData.PlaceDataProto.PlaceList buildPartial() {
        PlaceData.PlaceDataProto.PlaceList result = new PlaceData.PlaceDataProto.PlaceList(this);
        int from_bitField0_ = bitField0_;
        if (placeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            place_ = java.util.Collections.unmodifiableList(place_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.place_ = place_;
        } else {
          result.place_ = placeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlaceData.PlaceDataProto.PlaceList) {
          return mergeFrom((PlaceData.PlaceDataProto.PlaceList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlaceData.PlaceDataProto.PlaceList other) {
        if (other == PlaceData.PlaceDataProto.PlaceList.getDefaultInstance()) return this;
        if (placeBuilder_ == null) {
          if (!other.place_.isEmpty()) {
            if (place_.isEmpty()) {
              place_ = other.place_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlaceIsMutable();
              place_.addAll(other.place_);
            }
            onChanged();
          }
        } else {
          if (!other.place_.isEmpty()) {
            if (placeBuilder_.isEmpty()) {
              placeBuilder_.dispose();
              placeBuilder_ = null;
              place_ = other.place_;
              bitField0_ = (bitField0_ & ~0x00000001);
              placeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlaceFieldBuilder() : null;
            } else {
              placeBuilder_.addAllMessages(other.place_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPlaceCount(); i++) {
          if (!getPlace(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlaceData.PlaceDataProto.PlaceList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlaceData.PlaceDataProto.PlaceList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PlaceData.PlaceDataProto.Place> place_ =
        java.util.Collections.emptyList();
      private void ensurePlaceIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          place_ = new java.util.ArrayList<PlaceData.PlaceDataProto.Place>(place_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PlaceData.PlaceDataProto.Place, PlaceData.PlaceDataProto.Place.Builder, PlaceData.PlaceDataProto.PlaceOrBuilder> placeBuilder_;

      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public java.util.List<PlaceData.PlaceDataProto.Place> getPlaceList() {
        if (placeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(place_);
        } else {
          return placeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public int getPlaceCount() {
        if (placeBuilder_ == null) {
          return place_.size();
        } else {
          return placeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public PlaceData.PlaceDataProto.Place getPlace(int index) {
        if (placeBuilder_ == null) {
          return place_.get(index);
        } else {
          return placeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public Builder setPlace(
          int index, PlaceData.PlaceDataProto.Place value) {
        if (placeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlaceIsMutable();
          place_.set(index, value);
          onChanged();
        } else {
          placeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public Builder setPlace(
          int index, PlaceData.PlaceDataProto.Place.Builder builderForValue) {
        if (placeBuilder_ == null) {
          ensurePlaceIsMutable();
          place_.set(index, builderForValue.build());
          onChanged();
        } else {
          placeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public Builder addPlace(PlaceData.PlaceDataProto.Place value) {
        if (placeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlaceIsMutable();
          place_.add(value);
          onChanged();
        } else {
          placeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public Builder addPlace(
          int index, PlaceData.PlaceDataProto.Place value) {
        if (placeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlaceIsMutable();
          place_.add(index, value);
          onChanged();
        } else {
          placeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public Builder addPlace(
          PlaceData.PlaceDataProto.Place.Builder builderForValue) {
        if (placeBuilder_ == null) {
          ensurePlaceIsMutable();
          place_.add(builderForValue.build());
          onChanged();
        } else {
          placeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public Builder addPlace(
          int index, PlaceData.PlaceDataProto.Place.Builder builderForValue) {
        if (placeBuilder_ == null) {
          ensurePlaceIsMutable();
          place_.add(index, builderForValue.build());
          onChanged();
        } else {
          placeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public Builder addAllPlace(
          java.lang.Iterable<? extends PlaceData.PlaceDataProto.Place> values) {
        if (placeBuilder_ == null) {
          ensurePlaceIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, place_);
          onChanged();
        } else {
          placeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public Builder clearPlace() {
        if (placeBuilder_ == null) {
          place_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          placeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public Builder removePlace(int index) {
        if (placeBuilder_ == null) {
          ensurePlaceIsMutable();
          place_.remove(index);
          onChanged();
        } else {
          placeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public PlaceData.PlaceDataProto.Place.Builder getPlaceBuilder(
          int index) {
        return getPlaceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public PlaceData.PlaceDataProto.PlaceOrBuilder getPlaceOrBuilder(
          int index) {
        if (placeBuilder_ == null) {
          return place_.get(index);  } else {
          return placeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public java.util.List<? extends PlaceData.PlaceDataProto.PlaceOrBuilder> 
           getPlaceOrBuilderList() {
        if (placeBuilder_ != null) {
          return placeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(place_);
        }
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public PlaceData.PlaceDataProto.Place.Builder addPlaceBuilder() {
        return getPlaceFieldBuilder().addBuilder(
            PlaceData.PlaceDataProto.Place.getDefaultInstance());
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public PlaceData.PlaceDataProto.Place.Builder addPlaceBuilder(
          int index) {
        return getPlaceFieldBuilder().addBuilder(
            index, PlaceData.PlaceDataProto.Place.getDefaultInstance());
      }
      /**
       * <code>repeated .placedata.Place place = 1;</code>
       */
      public java.util.List<PlaceData.PlaceDataProto.Place.Builder> 
           getPlaceBuilderList() {
        return getPlaceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PlaceData.PlaceDataProto.Place, PlaceData.PlaceDataProto.Place.Builder, PlaceData.PlaceDataProto.PlaceOrBuilder> 
          getPlaceFieldBuilder() {
        if (placeBuilder_ == null) {
          placeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PlaceData.PlaceDataProto.Place, PlaceData.PlaceDataProto.Place.Builder, PlaceData.PlaceDataProto.PlaceOrBuilder>(
                  place_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          place_ = null;
        }
        return placeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:placedata.PlaceList)
    }

    // @@protoc_insertion_point(class_scope:placedata.PlaceList)
    private static final PlaceData.PlaceDataProto.PlaceList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlaceData.PlaceDataProto.PlaceList();
    }

    public static PlaceData.PlaceDataProto.PlaceList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PlaceList>
        PARSER = new com.google.protobuf.AbstractParser<PlaceList>() {
      public PlaceList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlaceList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlaceList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlaceList> getParserForType() {
      return PARSER;
    }

    public PlaceData.PlaceDataProto.PlaceList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_placedata_Place_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_placedata_Place_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_placedata_PlaceList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_placedata_PlaceList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017placedata.proto\022\tplacedata\">\n\005Place\022\r\n" +
      "\005state\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\013\n\003lat\030\003 \002(\001\022" +
      "\013\n\003lon\030\004 \002(\001\",\n\tPlaceList\022\037\n\005place\030\001 \003(\013" +
      "2\020.placedata.PlaceB\033\n\tPlaceDataB\016PlaceDa" +
      "taProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_placedata_Place_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_placedata_Place_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_placedata_Place_descriptor,
        new java.lang.String[] { "State", "Name", "Lat", "Lon", });
    internal_static_placedata_PlaceList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_placedata_PlaceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_placedata_PlaceList_descriptor,
        new java.lang.String[] { "Place", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
